### PR TITLE
Add the possibility to use openmp target to offload from sx-aurora to the host.

### PR DESCRIPTION
**Pull request by Sekuraz**
I want to show my current state.
It is working but documentation is lacking. I'll promote it to a request once i feel the documentation is appropriate.

### CODE REVIEW

**Comment by simoll** [comment]
Thanks for the PR! Is this now in a state where it can be reviewed or are you planning more changes?

**Comment by Sekuraz** [comment]
I'm only planning to improve documentation. So no actual coffee changes are planned.

**Comment by simoll** [comment]
I've rebased your commits onto `hpce/develop` . It's pushed as the `feature/vhoff` branch in this repository.
I'll add review comments once you've updated the PR.

Regarding the C++ issues, i guess you'll have to look into the way Clang set's up the invocation for the offload target. It looks as though flags that are only for the VE invocation are somehow carried over to the VH invocation (`-internal-isystem`).
You might want to have a look at the CUDA/HIP offloading support in Clang because sotoc does its own thing and x86 and ppc offloading are self-offloading to the same architecture (so same system include paths, etc).

**Comment by Sekuraz** [comment]
Pr is updated. But you can't change the source branch. So ich changed my ref in my repository. @simoll

**Comment by simoll** [comment]
The include path issue was fixed by https://github.com/sx-aurora-dev/llvm-project/commit/ce20dd1e5f8ecea6e100cbb0b6dddfd5709bffd9. This feature is now merged into `hpce/develop`. Thanks again for working the plugin!

**Pull request closed without merging**
