### PR TITLE
Merge/develop upstream 20220316

### PR DESCRIPTION
**Pull request by simoll**
Work in progress. Merge of recent upstream into 'develop' branch.

### CODE REVIEW

**Comment by simoll** [comment]
This passes all lit tests now. @kaz7 Could you have a look whether this is ready for merging into `develop`?

**Comment by kaz7** [comment]
Errors are:
```
Failed Tests (2):
  LLVM :: Verifier/vp-intrinsics-constrained.ll
  LLVM-Unit :: IR/./IRTests/VPIntrinsicTest.VPModuleComplete


Testing Time: 38.43s
  Skipped          :    60
  Unsupported      : 20977
  Passed           : 26844
  Expectedly Failed:    52
  Failed           :     2
  ```

**Comment by kaz7** [comment]
Other internal regression tests are passed.  On the other hand, we still have a lot of differences against upstream.
```
$ git diff 8dca38d53480 --stat
 llvm/include/llvm/Analysis/InstructionSimplify.h   |    14 +
 .../include/llvm/Analysis/LoopDependenceAnalysis.h |   108 +
 llvm/include/llvm/Analysis/LoopHotnessStats.h      |    32 +
 llvm/include/llvm/CodeGen/ISDOpcodes.h             |    13 +
 llvm/include/llvm/CodeGen/SelectionDAG.h           |    14 +
 llvm/include/llvm/CodeGen/SelectionDAGNodes.h      |    54 +
 llvm/include/llvm/CodeGen/TargetLowering.h         |    33 +-
 llvm/include/llvm/CodeGen/ValueTypes.h             |     3 +
 llvm/include/llvm/CodeGen/ValueTypes.td            |   242 +-
 llvm/include/llvm/IR/CallingConv.h                 |     4 +
 llvm/include/llvm/IR/FPEnv.h                       |    11 +-
 llvm/include/llvm/IR/IRBuilder.h                   |    26 +-
 llvm/include/llvm/IR/IntrinsicInst.h               |    68 +
 llvm/include/llvm/IR/Intrinsics.td                 |   164 +-
 llvm/include/llvm/IR/LLVMContext.h                 |     2 +
 llvm/include/llvm/IR/Operator.h                    |     8 +
 llvm/include/llvm/IR/VPBuilder.h                   |    76 +
 llvm/include/llvm/IR/VPIntrinsics.def              |   155 +-
 llvm/include/llvm/InitializePasses.h               |     2 +-
...
 llvm/include/llvm/Target/TargetSelectionDAG.td     |   119 +
 llvm/lib/Analysis/CMakeLists.txt                   |     2 +
 llvm/lib/Analysis/LoopDependenceAnalysis.cpp       |  2036 ++
 llvm/lib/Analysis/LoopHotnessStats.cpp             |   152 +
 llvm/lib/AsmParser/LLParser.cpp                    |     9 +-
 llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp    |     3 +
 llvm/lib/CodeGen/ExpandVectorPredication.cpp       |    74 +-
 llvm/lib/CodeGen/SelectionDAG/LegalizeDAG.cpp      |    57 +-
 .../CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp  |    23 +
 llvm/lib/CodeGen/SelectionDAG/LegalizeTypes.cpp    |    12 +-
 llvm/lib/CodeGen/SelectionDAG/LegalizeTypes.h      |     3 +
 .../lib/CodeGen/SelectionDAG/LegalizeVectorOps.cpp |    23 +
 .../CodeGen/SelectionDAG/LegalizeVectorTypes.cpp   |    43 +
 llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp     |    56 +
 .../CodeGen/SelectionDAG/SelectionDAGBuilder.cpp   |   136 +-
 .../lib/CodeGen/SelectionDAG/SelectionDAGBuilder.h |     3 +-
 llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp |     1 +
 llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp   |    59 +
 llvm/lib/CodeGen/TargetLoweringBase.cpp            |     5 +
...
 llvm/lib/IR/Attributes.cpp                         |     2 +-
 llvm/lib/IR/CMakeLists.txt                         |     1 +
 llvm/lib/IR/FPEnv.cpp                              |    20 +
 llvm/lib/IR/IRBuilder.cpp                          |    58 +
 llvm/lib/IR/IntrinsicInst.cpp                      |   191 +-
 llvm/lib/IR/LLVMContext.cpp                        |    10 +
 llvm/lib/IR/VPBuilder.cpp                          |   212 +
 llvm/lib/IR/Verifier.cpp                           |    78 +-
 llvm/lib/Passes/PassBuilder.cpp                    |     2 +
 llvm/lib/Passes/PassRegistry.def                   |     3 +
 llvm/lib/ProfileData/InstrProf.cpp                 |     2 +-
...
 .../3_lvl_3_dim-limited-by-z.ll                    |    74 +
 .../accesses-not-in-innermost-2.ll                 |    53 +
 .../accesses-not-in-innermost-3.ll                 |    65 +
 .../accesses-not-in-innermost.ll                   |    51 +
 .../LoopDependenceAnalysis/basic-4d-nest.ll        |    86 +
 .../Analysis/LoopDependenceAnalysis/clenshaw.ll    |    65 +
 .../definitely-vectorizable-3.ll                   |    53 +
 .../forward-dep-2D-illegal.ll                      |    77 +
 .../LoopDependenceAnalysis/forward-dep-2D.ll       |    56 +
 .../LoopDependenceAnalysis/forward-dep-illegal.ll  |    58 +
 .../Analysis/LoopDependenceAnalysis/forward-dep.ll |    44 +
 .../LoopDependenceAnalysis/global_array.ll         |    51 +
 .../imperfect-loop-nest-2.ll                       |    75 +
 .../imperfect-loop-nest-2_i32.ll                   |    96 +
 .../LoopDependenceAnalysis/imperfect-loop-nest.ll  |    70 +
 .../shuffled-squashing-illegal.ll                  |    71 +
 .../LoopDependenceAnalysis/shuffled-squashing.ll   |    69 +
 .../Analysis/LoopDependenceAnalysis/shuffled.ll    |    53 +
 .../Analysis/LoopDependenceAnalysis/squashing-2.ll |    73 +
 .../Analysis/LoopDependenceAnalysis/squashing.ll   |    68 +
 llvm/test/Bitcode/operand-bundles-bc-analyzer.ll   |     2 +
...
```

**Comment by simoll** [comment]
These are fixed now:
```
Failed Tests (2):
  LLVM :: Verifier/vp-intrinsics-constrained.ll
  LLVM-Unit :: IR/./IRTests/VPIntrinsicTest.VPModuleComplete
```

About the differences. What commit are you diffing against?

**Comment by kaz7** [comment]
I'll run internal regression tests tomorrow.
I ran `git diff 8dca38d53480...origin/merge/develop-upstream-20220316  --stat`

**Comment by kaz7** [comment]
@simoll can you push your patches?

**Comment by simoll** [comment]
> @simoll can you push your patches?

Pushed: b64459760cf7 & 75da3328021c

**Comment by kaz7** [comment]
Thanks.  I'm running internal regression tests.

**Comment by kaz7** [comment]
Passed all internal regression tests.  I'm merging this.

**Pull request merged**
