### PR TITLE
[VE] enable -ve-expensive-vector by default to discourage autovec

### PR DESCRIPTION
**Pull request by simoll**
Enable `-ve-expensive-vector` to not have automatic vectorization enabled by default on the `develop` branch.

### CODE REVIEW

**Comment by kaz7** [comment]
Thank you.  We have following new errors in check-llvm.

```
  LLVM :: CodeGen/VE/Packed/vec_gather_packed.ll
  LLVM :: CodeGen/VE/Packed/vec_scatter_packed.ll
  LLVM :: CodeGen/VE/Packed/vp-fparith-v512i32-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Packed/vp-reduce-v512i1-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Packed/vp-reduce-v512i32-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Packed/vp_fma_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_fms_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_fmsn_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_fpext_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_fptrunc_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_frcp_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_load_packed.ll
  LLVM :: CodeGen/VE/Packed/vp_store_packed.ll
  LLVM :: CodeGen/VE/Vector/vec_load.ll
  LLVM :: CodeGen/VE/Vector/vec_reduce_fadd.ll
  LLVM :: CodeGen/VE/Vector/vec_store.ll
  LLVM :: CodeGen/VE/Vector/vp-fparith-v256i64-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp-intarith-v256i64-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp-mem-v256i64-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp-reduce-v256i1-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp-reduce-v256i64-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp-v256i32-mask-avl-isel.ll
  LLVM :: CodeGen/VE/Vector/vp_add.ll
  LLVM :: CodeGen/VE/Vector/vp_and.ll
  LLVM :: CodeGen/VE/Vector/vp_ashr.ll
  LLVM :: CodeGen/VE/Vector/vp_fadd.ll
  LLVM :: CodeGen/VE/Vector/vp_fma.ll
  LLVM :: CodeGen/VE/Vector/vp_fms.ll
  LLVM :: CodeGen/VE/Vector/vp_fmsn.ll
  LLVM :: CodeGen/VE/Vector/vp_fneg.ll
  LLVM :: CodeGen/VE/Vector/vp_lshr.ll
  LLVM :: CodeGen/VE/Vector/vp_mul.ll
  LLVM :: CodeGen/VE/Vector/vp_or.ll
  LLVM :: CodeGen/VE/Vector/vp_sdiv.ll
  LLVM :: CodeGen/VE/Vector/vp_shl.ll
  LLVM :: CodeGen/VE/Vector/vp_srem.ll
  LLVM :: CodeGen/VE/Vector/vp_sub.ll
  LLVM :: CodeGen/VE/Vector/vp_udiv.ll
  LLVM :: CodeGen/VE/Vector/vp_urem.ll
  LLVM :: CodeGen/VE/Vector/vp_xor.ll
  LLVM :: Transforms/LoopVectorize/VE/disable_lv.ll
```

**Comment by kaz7** [comment]
Well, I've updated above regression tests.  After that, regression tests show more serious problem.  The performance of generated code is now 264% slower than before merging hpce/develop.  The code is implemented by using intrinsic instructions.
```
2 errors found
benchmark                                                                        a        b        diff     diff%   
Conv2D-32x256x34x34-512x256x4x4-32x512x31x31-1x1-1x1-0x0-1-1                       45.306   41.759    3.547    8.494 %
Conv2D-32x1024x14x14-2048x1024x1x1-32x2048x7x7-2x2-1x1-0x0-1-1                     20.374    5.594   14.780  264.212 %
```
It looks like VP generates spills in the loop.  We have no V64 or VP spills before in the generated code.  But now we have a lot. 
 Please check vml at your side and fix problems.
```
/usr/uhome/.../direct_...:246:5: warning: loop not unrolled: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
spill $v18 - V64
spill $vp9 - VP
restore $vp9 - VP
restore $v18 - V64
spill $v18 - V64
spill $vp9 - VP
restore $vp9 - VP
restore $v18 - V64
spill $v18 - V64
spill $vp9 - VP
restore $vp9 - VP
restore $v18 - V64
spill $v18 - V64
spill $vp9 - VP
restore $vp9 - VP
restore $v18 - V64
```

**Comment by simoll** [comment]
Appears to be fixed on my end with the latest commit. Could you re-check?

**Comment by kaz7** [comment]
Thank you for your help.  It passes performance test now.

I have following error on disable_lv.ll in llvm-test.  I tried to fix this, but it's difficult.  Can you inspect this one too?
```
/home/jenkins/workspace/oject_feature_no-default-autovec/llvm-project/llvm/test/Transforms/LoopVectorize/VE/disable_lv.ll:7:15: error: SCALAR-NOT: excluded string found in input
; SCALAR-NOT: llvm.loop.isvectorized
              ^
<stdin>:73:10: note: found here
!3 = !{!"llvm.loop.isvectorized", i32 1}
         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by simoll** [comment]
The loop is annotated as vectorized although there is only interleaving and no vector ops - improved the test to check for the absence of vector types instead of the `isvectorized` md node.

**Comment by kaz7** [comment]
Thanks.  But, now we are having this slowness again.  :-(
```
benchmark                                                                        a        b        diff     diff%   
Conv2D-32x256x34x34-512x256x4x4-32x512x31x31-1x1-1x1-0x0-1-1                       45.303   41.759    3.544    8.487 %
Conv2D-32x1024x14x14-2048x1024x1x1-32x2048x7x7-2x2-1x1-0x0-1-1                     20.305    5.594   14.711  262.978 %
```

**Comment by kaz7** [comment]
> But, now we are having this slowness again. :-(

It is the problem of my testing environment.  I've submitted a patch to fix it by #28.  Please review it, @simoll -san.  Thanks.

Then, problems I have with dea9255 is following:
- Regression test Exp problem
- Nightly test problem

Regarding to regression test, I have Exp error like below.  This program is slowed if I compare between 26852e9 and dea9255.
```
1 errors found
benchmark                                                                        a        b        diff     diff%   
Exp                                                                                 0.519    0.483    0.036    7.453 %
```

Regarding to nightly test, I have following errors.  Please ignore `minisat`, `Reductions-flt`, and `uint64_to_float` since those problems are caused by differences of hardware implementation.
```
FAIL: MultiSource/Applications/JM/lencod/lencod.execution_time (504 of 2515)
FAIL: MultiSource/Applications/minisat/minisat.execution_time (505 of 2515)
FAIL: MultiSource/Applications/oggenc/oggenc.execution_time (506 of 2515)
FAIL: MultiSource/Applications/sgefa/sgefa.execution_time (507 of 2515)
FAIL: MultiSource/Benchmarks/TSVC/ControlFlow-dbl/ControlFlow-dbl.execution_time (508 of 2515)
FAIL: MultiSource/Benchmarks/TSVC/ControlFlow-flt/ControlFlow-flt.execution_time (509 of 2515)
FAIL: MultiSource/Benchmarks/TSVC/Reductions-flt/Reductions-flt.execution_time (510 of 2515)
FAIL: SingleSource/Benchmarks/McGill/chomp.execution_time (511 of 2515)
FAIL: SingleSource/Benchmarks/Misc/ffbench.execution_time (512 of 2515)
FAIL: SingleSource/Benchmarks/Stanford/Puzzle.execution_time (513 of 2515)
FAIL: SingleSource/Regression/C/uint64_to_float.execution_time (514 of 2515)
```

**Comment by simoll** [comment]
Something weird is going on when the LoopVectorizer interleaves.. it appears to be breaking the IR (checked by cross-compiling bitcode for VE with the x86 backend)!
5481da7 disables interleaving in LV entirely on the VE (TTI change).. this solves the test-suite miscompiles, except for:

    FAIL: SingleSource/Regression/C/uint64_to_float.execution_time
    FAIL: MultiSource/Benchmarks/TSVC/Reductions-flt/Reductions-flt.execution_time
    FAIL: MultiSource/Applications/minisat/minisat.execution_time
    FAIL: MultiSource/Applications/spiff/spiff.execution_time

**Comment by kaz7** [comment]
Thanks.  I'm also running nightly test locally.

In addition, the latest change (5481da7) causes following error in check-llvm.
```
Failed Tests (1):
  LLVM :: Transforms/LoopVectorize/VE/disable_lv.ll
```

**Comment by kaz7** [comment]
When I test the latest change (5481da7) locally, it passes all nightly tests except following known issues.
```
FAIL: MultiSource/Applications/minisat/minisat.execution_time (504 of 2515)
FAIL: MultiSource/Benchmarks/TSVC/Reductions-flt/Reductions-flt.execution_time (505 of 2515)
FAIL: SingleSource/Regression/C/uint64_to_float.execution_time (506 of 2515)
```

**Comment by kaz7** [comment]
It's passing all except `disable_lv.ll` now.  Can you fix it @simoll -san?  And, please rebase and squash this branch to clean modifications.  After that, we can merge it and build rpm.  Thanks.

It's possible to fix `disable_lv.ll` by following patch, but it may be not what you want...
```
--- a/llvm/test/Transforms/LoopVectorize/VE/disable_lv.ll
+++ b/llvm/test/Transforms/LoopVectorize/VE/disable_lv.ll
@@ -1,5 +1,5 @@
 ; RUN: opt < %s  -loop-vectorize -ve-expensive-vector=1 -mtriple=ve-linux -S | FileCheck %s -check-prefix=SCALAR
-; RUN: opt < %s  -loop-vectorize -mtriple=ve-linux -S | FileCheck %s -check-prefix=VECTOR
+; RUN: opt < %s  -loop-vectorize -ve-expensive-vector=0 -mtriple=ve-linux -S | FileCheck %s -check-prefix=VECTOR
 ; RUN: opt < %s  -loop-vectorize -mtriple=x86_64-pc_linux -mcpu=core-avx2 -S | FileCheck %s -check-prefix=VECTOR

 ; LV must not trigger for VE if TTI is configured to make vector unappealing
```

**Comment by kaz7** [comment]
Thanks!! This passes all regression tests and nightly test.  I'm going to merge this.

**Pull request merged**
