### PR TITLE
[sotoc] Make compiler build-time configurable for nec-aurora-build wrapper

### PR DESCRIPTION
**Pull request by manorom**
This PR makes all three possible backend compilers, for sotoc  offloading, configurable at build time of the compiler with the CMake configuration variables 
`NECAURORA_TARGET_COMPILER_NCC`, `NECAURORA_TARGET_COMPILER_CLANG` and `NECAURORA_TARGET_COMPILER_RVCLANG`.

The CMake script will try to locate `NECAURORA_TARGET_COMPILER_NCC` at the standard install locations for `ncc`, (i.e. `/opt/nec/ve/...`) and set `NECAURORA_TARGET_COMPILER_CLANG` and `NECAURORA_TARGET_COMPILER_RVCLANG` to the install location of the llvm-project.

Please note, that there is not really a  'default'  compiler in the `nec-aurora-build` wrapper anymore because the Clang driver will always pass the `-fopenmp-nec-compiler` option to the wrapper.

I submit this as a draft, because I would like to propose `-fopenmp-nec-compiler` accepting an arbitrary path or command as backend compiler.
This would be helpful for us running the sotoc tests with compilers other then `ncc` because `clang` and `rvclang` might not be copied to the install location when the test suite is run (and we then might use older versions of the compiler to run the test without noticing).

### CODE REVIEW

**Comment by simoll** [comment]
Thanks for the PR!
I'd like to have both, an easy way to switch between the three compiler presets as it is implemented now, and allowing a path to the target compiler on the clang command line.
Regarding syntax, how about we go with something like this: `-fopenmp-nec-compiler=path:/path/to/my/favorite/target/compiler`.

**Comment by manorom** [comment]
@simoll I should have been clearer, I too would like to keep the presets.

Now I originally thought that `nec-aurora-build` could just use whatever is passed to it with the `-fopenmp-nec-compiler` switch as compiler if it does not recognize it as a preset.

But if, for example, another clang installation is used as backend compiler, then the wrapper not only needs the path but also the `--target=ve-linux` flag.
So I wasn't really sure what the commandline syntax for that should be.

**Comment by simoll** [comment]
> @simoll I should have been clearer, I too would like to keep the presets.
> 
> Now I originally thought that `nec-aurora-build` could just use whatever is passed to it with the `-fopenmp-nec-compiler` switch as compiler if it does not recognize it as a preset.

Yep, we have the same idea here. Only difference is that the tool would only recognize it as a path when it is prefixed with `path:` and as a preset otherwise. This is a precaution to make sure the behavior does not change in case another preset was added that has the same name as someone's compiler binary.

> 
> But if, for example, another clang installation is used as backend compiler, then the wrapper not only needs the path but also the `--target=ve-linux` flag.
> So I wasn't really sure what the commandline syntax for that should be.

Couldn't you just forward the `-Xopenmp-target` options to the target compiler?

**Comment by manorom** [comment]
Sorry for not coming back to this earlier. I have implemented the syntax you proposed now.

**Comment by simoll** [comment]
No worries, it's there in time for the next release :) I'll ping you when the pre-release branches are ready for testing.

**Pull request merged**
