### PR TITLE
[VE] group tests into Scalar,Vector and VELIntrinsic folders

### PR DESCRIPTION
**Pull request by simoll**
This helps with selective testing of the SPU, VPU, intrinsic support by naming the folders.

### CODE REVIEW

**Comment by kaz7** [comment]
@simoll, can you rebase this one to resolve conflicts?   Thank you.

**Comment by simoll** [comment]
Rebased it

**Comment by jam7** [comment]
Thanks!  merged.

**Comment by jam7** [comment]
We've merged this PR.  However, now we departed from upstream/master.  Is it possible to send similar PR to upstream?

**Pull request merged**
